name: ragnarec
channels:
    - pytorch
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - numpy
    - toolz
    - matplotlib
    - pandas
    - pip
    - pytorch
    - nltk
    - ipykernel
    - gensim
    - cython
    - spacy
    - pip:
          - regex
          - transformers
          - pyarrow
          - fastparquet
          - scikit-learn
          - bertopic
