name: ragnarec
channels:
    - pytorch
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - numpy
    - toolz
    - matplotlib
    - pandas
    - pip
    - pytorch
    - nltk
    - ipykernel
    - gensim
    - cython
    - spacy
    - textblob
    - seaborn
    - pip:
          - regex
          - transformers
          - pyarrow
          - fastparquet
          - scikit-learn
          - bertopic
          - langchain
          - langchain-community
          - langchain-openai
          - langchain-chroma
          - sentence-transformers
          - chromadb
          - vadersentiment